language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
sudo: false
notifications:
  email: false
before_install:
  - npm install -g gulp
  - npm install codecov.io
install:
  - npm install --ignore-scripts
after_success:
  - "cat ./coverage/coverage-final.json | ./node_modules/codecov.io/bin/codecov.io.js"
